export { default as CompareSlider } from "./CompareSlider/CompareSlider";
export { default as Footer } from "./Footer/Footer";
export { default as Header } from "./NavBar/NavBar";
export { default as DesktopNavBar } from "./NavBar/DesktopNavBar/DesktopNavBar";
export { default as MobileNavBar } from "./NavBar/MobileNavBar/MobileNavBar";
export { default as LangPopup } from "./LangPopup/LangPopup";
export { default as LangSwitcher } from "./LangSwitcher/LangSwitcher";
export { default as NavDrawer } from "./NavDrawer/NavDrawer";
export { default as ThemeSwitcher } from "./ThemeSwitcher/ThemeSwitcher";
